console.log("SOMA: ", 5 + 3 + 8)
console.log("CONCATENAÇÃO: ", 5 + "5")
console.log("DIVISÃO: ", 10 / 3)
console.log("MULTIPLICAÇÃO: ", 10 * 3)
console.log("RESTO DA DIVISÃO: ", 10 % 3)
console.log("EXPONENCIAL: ", 2 ** 3)